### ISSUE TITLE
Can you add a pic about alipay

### ISSUE THREAD

**Issue by phpgao** [nullice/NViconsLib_Silhouette#4]

**Comment by nullice** [comment]
That some late, but now with alipay icon
![](https://github.com/nullice/NViconsLib_Silhouette/raw/master/Sample/sample_flat_2/%E5%9C%86%E5%BD%A2_/64px/Alibabai_Alipay.png)
![](https://raw.githubusercontent.com/nullice/NViconsLib_Silhouette/master/svg/CN_Alibabai_Alipay.svg)
https://github.com/nullice/NViconsLib_Silhouette/raw/master/svg/CN_Alibabai_Alipay.svg

**Comment by phpgao** [comment]
Good job ! THX a lot!
